project:
  type: website
  output-dir: docs

website:
  title: "David Roycroft"
  navbar: 
    search: true
    right:
      - about.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/DRoycroft
      - icon: twitter
        href: https://twitter.com/DavidRoycroft6
format:
  html:
    theme: cyborg
    css: styles.css



